<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>

    <!-- EXE name -->
    <AssemblyName>r4ns0m</AssemblyName>
    <RootNamespace>r4ns0m</RootNamespace>

    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>

    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\**\*.*">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.0.1" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
  </ItemGroup>

</Project>