<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>

    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>

    <!-- EXE name -->
    <AssemblyName>r4ns0m</AssemblyName>
    <RootNamespace>r4ns0m</RootNamespace>

    <!-- Windows Explorer file metadata -->
    <Product>r4ns0m</Product>
    <Title>r4ns0m</Title>
    <Description>A recreation of Ransom entity from Roblox DOORS</Description>
    <FileDescription>A recreation of Ransom entity from Roblox DOORS</FileDescription>

    <Version>2.1.0.0</Version>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <FileVersion>2.1.0.0</FileVersion>

    <Company>MurderCube_K59</Company>
    <Copyright>MurderCube_K59</Copyright>

    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>

    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\**\*.*">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.0.1" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
  </ItemGroup>

</Project>